version: '3.8'

services: 
  fm_frontend:
    image: nstoik/fm_frontend:latest
    container_name: fm_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5000:5000/tcp
    networks:
      - farm_monitor

networks:
  farm_monitor:
    external: true