version: '2'

services: 
  fm_frontend:
    image: nstoik/fm_frontend:latest
    container_name: fm_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5000:5000/tcp
    networks:
      - farm_monitor
    depends_on:
      - "db"
  db:
    image: postgres:11
    container_name: "db"
    restart: always
    environment:
      POSTGRES_PASSWORD: farm_monitor
      POSTGRES_USER: fm
      POSTGRES_DB: farm_monitor.db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - farm_monitor
  
volumes:
  dbdata:

networks:
  farm_monitor: